Radxa rock pi e
RadxaYuntian/mraa pull request #10
Opened 2023-12-14 11:57 UTC by nascs

2023-12-15 07:27 UTC, RadxaYuntian requested changes

2023-12-15 07:27 UTC, RadxaYuntian commented on README.md
> +* [Radxa ROCK PI E](../master/docs/radxa_rock_pi_e.md)
```suggestion
* [Radxa ROCK Pi E](../master/docs/radxa_rock_pi_e.md)
```

2023-12-15 07:27 UTC, RadxaYuntian commented on api/mraa/types.h
> + *  Radxa ROCK PI E GPIO numbering enum
```suggestion
 *  Radxa ROCK Pi E GPIO number enum
```

2023-12-15 07:27 UTC, RadxaYuntian commented on api/mraa/types.hpp
> +    RADXA_ROCK_PI_E = 36,        /**< Radxa ROCK PI E */
```suggestion
    RADXA_ROCK_PI_E = 36,        /**< Radxa ROCK Pi E */
```

2023-12-15 07:27 UTC, RadxaYuntian commented on docs/radxa_rock_pi_e.md
> +Radxa ROCK PI E {#_Radxa}
```suggestion
Radxa ROCK Pi E {#_Radxa}
```

2023-12-15 07:27 UTC, RadxaYuntian commented on docs/radxa_rock_pi_e.md
> +Radxa ROCK PI E is a Rockchip RK3288 based SBC(Single Board Computer) by Radxa. It can run Android or Linux.
```suggestion
Radxa ROCK Pi E is a Rockchip RK3288 based single board computer by Radxa. It can run Android or Linux.
```

2023-12-15 07:27 UTC, RadxaYuntian commented on docs/radxa_rock_pi_e.md
> +Radxa ROCK PI E has a 40-pin expansion header. Each pin is distinguished by the color.
```suggestion
Radxa ROCK Pi E has a 40-pin expansion header. Each pin is distinguished by the color.
```

2023-12-15 07:27 UTC, RadxaYuntian commented on docs/radxa_rock_pi_e.md
> +- [Forums](https://forum.radxa.com/c/rock3)
3C?

2023-12-15 07:27 UTC, RadxaYuntian commented on src/arm/arm.c
> -            platform_type = MRAA_RADXA_ROCK_3B;
怎么删掉了？

2023-12-15 07:27 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> -    mraa_radxa_cm3_pininfo(b, 8, 0, 25, (mraa_pincapabilities_t){1,0,0,0,0,0,0,1}, "GPIO0_D1"); // GPIO0_D1 was used by fiq_debugger, function GPIO cannot be enabled
UART8和10的改动先不要提，这里涉及到硬件默认是不支持这两个引脚的问题，可能需要加上硬件功能识别

2023-12-15 07:27 UTC, RadxaYuntian commented on src/arm/radxa_rock_pi_e.c
> +    pininfo->gpio.mux_total = 0;
mux_total是什么用处?

2023-12-15 07:27 UTC, RadxaYuntian commented on src/arm/radxa_rock_pi_e.c
> +    mraa_radxa_rock_pi_e_pininfo(b, 8, 2, 0, (mraa_pincapabilities_t){1,1,0,0,0,0,0,1}, "GPIO2_A0");
可以暂时先和其他产品保持一致，关闭pin 8和10

2023-12-27 06:22 UTC, RadxaYuntian requested changes

2023-12-27 06:22 UTC, RadxaYuntian commented on docs/radxa_rock_pi_e.md
> +- [Forums](https://forum.radxa.com/c/rock3)
链接还是没有修改

2023-12-27 06:22 UTC, RadxaYuntian commented on src/arm/radxa_rock_pi_e.c
> +    mraa_radxa_rock_pi_e_pininfo(b, 8, 2, 0, (mraa_pincapabilities_t){1,1,0,0,0,0,0,1}, "GPIO2_A0");
3328有开启pin 8和10的gpio了么？

2023-12-27 06:26 UTC, nascs commented on src/arm/radxa_rock_pi_e.c
> +    mraa_radxa_rock_pi_e_pininfo(b, 8, 2, 0, (mraa_pincapabilities_t){1,1,0,0,0,0,0,1}, "GPIO2_A0");
rock pi e 的 pin 8 & pin 10 不影响 gpio 的使用

2024-01-02 09:48 UTC, nascs commented
gpio pull up/down 的修改，我也在这个分支该吧，然后一起提交上去

2024-01-02 09:49 UTC, RadxaYuntian commented on src/arm/radxa_rock_pi_e.c
> +    pininfo->gpio.mux_total = 0;
mux_total是什么用处?

2024-01-02 09:50 UTC, RadxaYuntian commented
如果你要在这里修改那跟客户回复一下

2024-01-02 09:59 UTC, nascs commented on src/arm/radxa_rock_pi_e.c
> +    pininfo->gpio.mux_total = 0;
有点类似于寄存器的 pinmux

2024-01-04 02:02 UTC, nascs commented
按照那个客户的代码做了一个测试，打开一个 spi 后设置 cs 脚为输出再上拉，是可以的

2024-01-04 02:11 UTC, nascs commented
https://github.com/haelyons/mraa-spi-oled/blob/master/remora_rock_hal.c

2024-01-04 11:21 UTC, haelyons commented
Tested by cross-compiling commit `0f1a43` with pull up / down changes, still receiving `Not Implemented` error when running `status = mraa_gpio_mode(dc, MRAA_GPIO_PULLUP);`. Can confirm that changes were correctly applied (as below lines are visible in `/usr/include/linux/gpio.h` on target.
```
#define GPIOHANDLE_REQUEST_BIAS_PULL_UP (1UL << 5)
#define GPIOHANDLE_REQUEST_BIAS_PULL_DOWN (1UL << 6)
```

2024-01-04 11:43 UTC, nascs commented
Hi @haelyons Can you help me test commit [df94ff9](https://github.com/RadxaYuntian/mraa/pull/10/commits/df94ff947f4034498ae1c747032c35505d9f0a84)？

2024-01-04 12:28 UTC, haelyons commented
Still getting the `Not Implemented` error on `status = mraa_gpio_mode(dc, MRAA_GPIO_PULLUP);`, doing a full rebuild to see if this is on my side.

2024-01-04 12:33 UTC, nascs commented
I'm not getting a Not Implemented error, but I'm not currently passing the test, so I'm not sure my test method is working.

2024-01-04 12:37 UTC, nascs commented
Did you test the code with branch [Radxa_ROCK_PI_E](https://github.com/nascs/mraa/tree/Radxa_ROCK_PI_E) ?

2024-01-04 12:41 UTC, haelyons commented
Yes, directly used latest commit `df94ff` with mraa makefile to cross-compile for aarch64 (Rock 3A). All files look correct in place, full rebuild eta 40 min.

2024-01-04 13:22 UTC, haelyons commented
Maybe issue with my setup -- should all files under `mraa/include/` be included in root filesystem in `/usr/include/`? 

I was only previously using makefile to write the `/usr/include/linux/gpio.h`. As such I am missing `gpio_chardev.h` from `/usr/include/gpio/`.

2024-01-04 16:18 UTC, haelyons commented
From `/tmp/messages` syslog:
```
Aug  4 09:00:51 smc local1.notice libmraa[241]: libmraa version 2022.08.1 initialised by user 'root' with EUID 0
Aug  4 09:00:51 smc local1.notice libmraa[241]: gpio: support for chardev interface is activated
Aug  4 09:00:51 smc local1.notice libmraa[241]: libmraa initialised for platform 'Radxa ROCK3 Model A' of type 35
Aug  4 09:00:51 smc local1.err libmraa[241]: [GPIOD_INTERFACE]: ioctl() error Invalid argument
Aug  4 09:00:51 smc local1.err libmraa[241]: gpiod: ioctl() fail
Aug  4 09:00:51 smc local1.err libmraa[241]: [GPIOD_INTERFACE]: error getting line handle
```

2024-01-04 17:54 UTC, haelyons commented
Where is the actual implementation of pull / up down behaviour to communicate to gpio controller (`gpio-rockchip.c`?)? I can see ioctl() error in gpio_chardev.c in `status = ioctl(fd, gpio_request, data);`.

2024-01-04 18:16 UTC, haelyons commented
I am using kernel 4.19 (see https://github.com/radxa/kernel/blob/stable-4.19-rock3/drivers/gpio/gpiolib.c) -- the valid flags don't include those that were added to the headers in your commit, as you can see below:

```
#define GPIOHANDLE_REQUEST_VALID_FLAGS \
	(GPIOHANDLE_REQUEST_INPUT | \
	GPIOHANDLE_REQUEST_OUTPUT | \
	GPIOHANDLE_REQUEST_ACTIVE_LOW | \
	GPIOHANDLE_REQUEST_OPEN_DRAIN | \
	GPIOHANDLE_REQUEST_OPEN_SOURCE)
```

What kernel version are you using?

2024-01-05 02:20 UTC, RadxaYuntian commented
We are using 5.10 rkr4.1 branch for 3A.

2024-01-05 02:22 UTC, RadxaYuntian commented
@nascs need to add a compile switch to turn on pullup support optionally, as not all kernel supports this feature.

2024-01-05 02:25 UTC, nascs commented
> I am using kernel 4.19 (see https://github.com/radxa/kernel/blob/stable-4.19-rock3/drivers/gpio/gpiolib.c) -- the valid flags don't include those that were added to the headers in your commit, as you can see below:
> 
> ```
> #define GPIOHANDLE_REQUEST_VALID_FLAGS \
> 	(GPIOHANDLE_REQUEST_INPUT | \
> 	GPIOHANDLE_REQUEST_OUTPUT | \
> 	GPIOHANDLE_REQUEST_ACTIVE_LOW | \
> 	GPIOHANDLE_REQUEST_OPEN_DRAIN | \
> 	GPIOHANDLE_REQUEST_OPEN_SOURCE)
> ```
> 
> What kernel version are you using?

I'm using Linux 5.10, and the GPIO interface currently used by mraa is gpiod.

2024-01-05 10:41 UTC, haelyons commented
Ok will either add support for pull-ups to 4.19 or upgrade to kernel 5.10, and test with mraa again, thanks.

2024-01-05 11:52 UTC, RadxaYuntian commented
We are using that branch but I'd suggest you just upgrade the kernel as a whole. Picking code like that can cause a lot of issues.

2024-01-05 13:03 UTC, haelyons commented
~~Which uboot version are you using for 5.10 on Rock 3A? Only 5.10 seems to be for Rock5 -- https://github.com/radxa/u-boot.git. I am currently using [stable-4.19-rock3](https://github.com/radxa/u-boot/compare/stable-4.19-rock3) branch of radxa/u-boot~~

Built and working with 5.10, getting unknown platform error, have not changed ~make~ from previous version. In any case thanks for your help, will continue troubleshooting.

2024-01-08 02:27 UTC, RadxaYuntian commented
Please use our latest released image: https://github.com/radxa-build/rock-3a/releases/download/b25/rock-3a_debian_bullseye_xfce_b25.img.xz

2024-01-08 12:29 UTC, haelyons commented
I am building a custom Rock 3A image in Buildroot, cannot use the Debian image for my purposes.

2024-01-08 12:30 UTC, RadxaYuntian commented
We are currently using this branch for all non RK3588 products: https://github.com/radxa/u-boot/tree/rk3568-2023.10

2024-01-09 12:15 UTC, haelyons commented
Ok building with this. Would it be possible to provide the specific u-boot configuration for the RK3568, for example as used in your Debian image?

2024-01-10 02:08 UTC, RadxaYuntian commented
`rock-3a-rk3568_defconfig` is the correct file. The warning is normal, since the original file could be maintained be 3rd party with various level of feature support, when we want to enable certain features across SoC, some configs could already be enabled in the file.

We do have some additional configs that are enabled for all our products. Since maintaining and editing 20+ files whenever we need to change global settings is a pain, they are [stored separately](https://github.com/radxa-repo/bsp/blob/main/u-boot/.common/kconfig.conf) and are applied by our build script at build time.

2024-01-10 16:34 UTC, haelyons commented
Thank this was very helpful, configuration is correct (tested against radxa bsp tools). Can you confirm which ddr binary (from `rkbin/bin/rk35/rk3568-ddr-*`) should be used for this version (if any)? 

Here is my related error in Buildroot (as we are using binman):
```
Image 'simple-bin' is missing external blobs and is non-functional: rockchip-tpl

/binman/simple-bin/mkimage/rockchip-tpl (rockchip-tpl):
   An external TPL is required to initialize DRAM. Get the external TPL
   binary and build with ROCKCHIP_TPL=/path/to/ddr.bin. One possible source
   for the external TPL binary is https://github.com/rockchip-linux/rkbin.

Image 'simple-bin' is missing optional external blobs but is still functional: tee-os

/binman/simple-bin/fit/images/@tee-SEQ/tee-os (tee-os):
   See the documentation for your board. You may need to build Open Portable
   Trusted Execution Environment (OP-TEE) and build with TEE=/path/to/tee.bin

Image 'simple-bin-spi' is missing external blobs and is non-functional: rockchip-tpl

/binman/simple-bin-spi/mkimage/rockchip-tpl (rockchip-tpl):
   An external TPL is required to initialize DRAM. Get the external TPL
   binary and build with ROCKCHIP_TPL=/path/to/ddr.bin. One possible source
   for the external TPL binary is https://github.com/rockchip-linux/rkbin.

Some images are invalid
```

2024-01-11 02:10 UTC, RadxaYuntian commented
rkbin is pulled in [this command](https://github.com/radxa-repo/bsp/blob/main/u-boot/.rockchip/rkbin.sh#L10). BL2 (ddr bin) and BL31 are filtered with [the following file name pattern](https://github.com/radxa-repo/bsp/blob/main/u-boot/latest/fork.conf#L101-L102) and the latest one is [determined by string sorting](https://github.com/radxa-repo/bsp/blob/main/lib/u-boot.sh#L88).

2024-01-11 17:37 UTC, haelyons commented
Thank you, successfully built kernel 5.10 and bootloader 23.10. Still receiving the `Unknown platform` when running `mraa-gpio`, will look more into it tomorrow.

2024-01-12 02:18 UTC, RadxaYuntian commented
mraa determines the platform by device tree's model field:

https://github.com/eclipse/mraa/blob/master/include/arm/radxa_rock_3a.h#L23

https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr4.1/arch/arm64/boot/dts/rockchip/rk3568-rock-3a.dts#L18

Did you change this value?

2024-01-12 13:10 UTC, haelyons commented
Have not changed the  mraa header. The compatible file under `/proc/device-tree/compatible` reads `radxa,rock-3arockchip,rk3568` which is correct. Perhaps this is an issue with the installation of mraa onto the board, though it worked on 4.19 which is strange. See `/var/log/messages` -- https://github.com/haelyons/mraa-spi-oled/commit/32c23b85f62424023157bf4efdd74e8b47b6905f

2024-01-15 02:33 UTC, RadxaYuntian commented
Your issue is likely due to SPI overlay not loaded, so you can check the our available overlays here: https://github.com/radxa/overlays/tree/main/arch/arm64/boot/dts/rockchip/overlays

All our overlays contain a compatible field for you to check whether they could be used with 3A.

 FIQ Debugger is not the same as UART. You should use `rk3568-uart2-m0` in your example.

2024-01-15 16:12 UTC, haelyons commented
The issue was that I was using `.dts` as opposed to `.dtbo` overlays, and my serial cable was broken, so nothing on this side. All GPIOs working, overlays loaded correctly, and can assign pull-ups. Thank you for the help :)

2024-03-01 02:34 UTC, RadxaYuntian commented
新产品开个新分支去处理

2024-03-06 10:15 UTC, RadxaYuntian requested changes

2024-03-06 10:15 UTC, RadxaYuntian commented on docs/radxa_rock_pi_e.md
> +- [Product Info](https://docs.radxa.com/rockpi/e)
```suggestion
- [Product Info](https://docs.radxa.com/rockpi/rockpie)
```

2024-03-06 10:15 UTC, RadxaYuntian commented on include/arm/radxa_rock_pi_e.h
> +#define MRAA_RADXA_ROCK_PI_E_AIO_COUNT  1
MRAA是不是有AIO的支持，好像后面没有添加这个引脚的功能

2024-03-06 10:15 UTC, RadxaYuntian commented on api/mraa/gpio.h
> +    MRAA_GPIO_DISABLE = 7,
```suggestion
    MRAA_GPIOD_BIAS_DISABLE = 7,
```
你这是个gpiod独有的功能，不是通用的属性

2024-03-06 10:15 UTC, RadxaYuntian commented on include/linux/gpio.h
间隔对齐

2024-03-06 10:15 UTC, RadxaYuntian commented on include/gpio/gpio_chardev.h
> +mraa_boolean_t mraa_is_gpio_line_disable(mraa_gpiod_line_info *linfo);
```suggestion
mraa_boolean_t mraa_is_gpio_line_bias_disable(mraa_gpiod_line_info *linfo);
```

2024-03-06 10:15 UTC, RadxaYuntian commented on src/gpio/gpio.c
> +                break;
```suggestion
```
这个需要底层的驱动支持，但sysfs驱动压根就不支持这个值：https://docs.yoctoproject.org/pipermail/linux-yocto/2016-March/004766.html
gpio_drive_show函数

2024-03-06 10:15 UTC, RadxaYuntian commented on src/gpio/gpio_chardev.c
> +mraa_is_gpio_line_disable(mraa_gpiod_line_info* linfo)
```suggestion
mraa_is_gpio_line_bias_disable(mraa_gpiod_line_info* linfo)
```

2024-03-07 03:39 UTC, RadxaYuntian requested changes

2024-03-07 03:39 UTC, RadxaYuntian commented on src/gpio/gpio.c
> -            case MRAA_GPIO_DISABLE:
你这不是应该用MRAA_GPIOD_BIAS_DISABLE么？是下面那个非chardev_capable才没有啊！

2024-03-07 03:40 UTC, RadxaYuntian commented on include/linux/gpio.h
还是没对其

2024-03-07 08:54 UTC, RadxaYuntian approved these changes
自测一下，确认没问题就可以squash提交给上游了

2024-03-07 08:54 UTC, closed without merging