platform: add radxa e25 support
RadxaYuntian/mraa pull request #11
Opened 2024-01-12 08:08 UTC by nascs

用的是 6.1 内核测的

2024-01-12 08:22 UTC, RadxaYuntian commented
顺便看一下我们的rkr4.1分支的model以及compatible是不是和上游一致

2024-01-13 13:41 UTC, nascs commented
> 顺便看一下我们的rkr4.1分支的model以及compatible是不是和上游一致

一致的

2024-01-15 08:41 UTC, RadxaYuntian requested changes

2024-01-15 08:41 UTC, RadxaYuntian commented on api/mraa/types.hpp
> +
额外空行

2024-01-15 08:41 UTC, RadxaYuntian commented on include/arm/radxa_e25.h
> +#define PLATFORM_NAME_RADXA_E25_1 "Radxa E25"
这是什么镜像的model

2024-01-15 08:41 UTC, RadxaYuntian commented on include/arm/radxa_e25.h
> +#define MRAA_RADXA_E25_UART_COUNT 4
后面只有3个

2024-01-15 08:42 UTC, RadxaYuntian commented on src/arm/radxa_e25.c
> +    b->pwm_max_period = 2147483;
是不是[2147483647](https://en.wikipedia.org/wiki/2,147,483,647)？

2024-01-15 08:46 UTC, nascs commented on include/arm/radxa_e25.h
> +#define PLATFORM_NAME_RADXA_E25_1 "Radxa E25"
rkr4.1 和上游的是 "Radxa E25 Carrier Board"， 以前 4.19 的是 "Radxa E25"

2024-01-15 08:52 UTC, RadxaYuntian commented on include/arm/radxa_e25.h
> +#define PLATFORM_NAME_RADXA_E25_1 "Radxa E25"
以前的就不支持了

2024-01-17 06:46 UTC, RadxaYuntian commented
改完了再强推

2024-01-17 06:47 UTC, RadxaYuntian commented on src/arm/radxa_e25.c
> +    b->pwm_max_period = 2147483;
所以你这个2147483是怎么来的？

2024-01-17 06:51 UTC, nascs commented on src/arm/radxa_e25.c
> +    b->pwm_max_period = 2147483;
抄 rockpi4.c 里面的

2024-01-17 06:58 UTC, RadxaYuntian requested changes

2024-01-17 06:58 UTC, RadxaYuntian commented on api/mraa/types.h
> +    MRAA_RADXA_E25 = 37,            /**< Radxa E25 */
```suggestion
    MRAA_RADXA_E25 = 36,            /**< Radxa E25 */
```
中间不要跳过

2024-01-17 06:58 UTC, RadxaYuntian commented on api/mraa/types.hpp
> +    RADXA_E25 = 37,            /**< Radxa E25 */
```suggestion
    RADXA_E25 = 36,            /**< Radxa E25 */
```

2024-01-17 06:58 UTC, RadxaYuntian commented on docs/radxa_e25.md
> +- [Product Info](https://docs.radxa.com/en/compute-module/e25)
地址按照文档群里面说的更新

2024-01-17 06:58 UTC, RadxaYuntian commented on docs/radxa_e25.md
> +Radxa E25 {#_Radxa}
需要注明Radxa E25 V1.3是不支持的，只支持1.4及之后的版本

2024-01-17 06:58 UTC, RadxaYuntian commented on include/arm/radxa_e25.h
> +#define MRAA_RADXA_E25_PIN_COUNT  40
```suggestion
#define MRAA_RADXA_E25_PIN_COUNT  26
```

2024-01-17 07:52 UTC, RadxaYuntian commented on src/arm/radxa_e25.c
> +    b->pwm_max_period = 2147483;
看了下别的产品，好像也都没啥规律

2024-01-17 08:54 UTC, nascs commented on api/mraa/types.h
> +    MRAA_RADXA_E25 = 37,            /**< Radxa E25 */
这个是因为 rock pi e 是 36

2024-01-17 09:15 UTC, RadxaYuntian commented on api/mraa/types.h
> +    MRAA_RADXA_E25 = 37,            /**< Radxa E25 */
你现在如果先提交这个的话要改回去

2024-01-17 11:18 UTC, nascs commented on api/mraa/types.h
> +    MRAA_RADXA_E25 = 37,            /**< Radxa E25 */
打算先提交 rock pi e，可以先审那个

2024-01-17 11:41 UTC, nascs commented on api/mraa/types.h
> +    MRAA_RADXA_E25 = 37,            /**< Radxa E25 */
emm, 看了一下邮件，e25 那个客户好像在催，还是先提这个吧

2024-01-18 02:48 UTC, RadxaYuntian commented on docs/radxa_e25.md
> +Radxa E25 {#_Radxa}
这个还没处理

2024-01-18 06:45 UTC, nascs commented on docs/radxa_e25.md
> +Radxa E25 {#_Radxa}
在这标明了
[radxa e25: fix step 2](https://github.com/RadxaYuntian/mraa/pull/11/commits/8cd1282ad1b22c754f1f85a25d4bc0f8ed47634e)

2024-01-18 06:51 UTC, RadxaYuntian requested changes

2024-01-18 06:51 UTC, RadxaYuntian commented on docs/radxa_e25.md
> +- Radxa E25 V1.3 is not supported, only versions 1.4 and later are supported.
```suggestion
- Radxa E25 v1.3 or earlier with 10-pin header are **NOT** supported. Only v1.4 or later with 26-pin header are supported.
```

2024-01-18 06:51 UTC, RadxaYuntian commented
整理一下，然后准备提交给上游吧

2024-01-18 06:51 UTC, closed without merging