Pwm issue
RadxaYuntian/mraa pull request #12
Opened 2024-02-04 06:35 UTC by nascs

5a/5b/3c/cm3 pwm 都用 led 重新测了一遍，3c pin 19 那个 pwm15_m0 被 fan0 占用

2024-02-04 06:47 UTC, RadxaYuntian requested changes

2024-02-04 06:47 UTC, RadxaYuntian commented on src/arm/radxa_rock_3c.c
>      b->pins[23].pwm.mux_total = 0;
为什么这里没有pwm.pinmap = 0

2024-02-04 06:47 UTC, RadxaYuntian commented on src/arm/radxa_rock_5a.c
> +    b->pins[24].pwm.parent_id = 1;   // PWM1_M2
你有的时候是按照pwm的硬件编号排序，有的时候是按pin的编号排序。那你自己要遵守你自己原有的排序规则

2024-02-04 07:11 UTC, nascs commented on src/arm/radxa_rock_5a.c
> +    b->pins[24].pwm.parent_id = 1;   // PWM1_M2
那后面统一按照 pin 的顺序编号来吧

2024-02-04 07:51 UTC, RadxaYuntian commented on src/arm/radxa_rock_5a.c
> +    b->pins[24].pwm.parent_id = 1;   // PWM1_M2
你现在这个先改了

2024-02-04 07:52 UTC, RadxaYuntian commented
所以是必须要加上这个pwm.pinmap才能使用pwm么？这个应该是在结构分配内存时自动赋0了吧？

2024-02-04 11:19 UTC, nascs commented
> 所以是必须要加上这个pwm.pinmap才能使用pwm么？这个应该是在结构分配内存时自动赋0了吧？

上周， 看 ROCK 3C 的 pin 7 脚 pwm 无法使用，后面加上 pwm.pinmap 就能用，但是今天的情况就是加不加都能用，打印了 board->pins[pin].pwm.pinmap 默认会初始化为 0，所以应该是不加也行

2024-02-04 11:26 UTC, RadxaYuntian commented
所以还是没搞清楚为什么pwm不行咯

2024-02-05 02:44 UTC, RadxaYuntian commented
已有文件的顺序就别改了吧，回头可以单独弄一个formatting的PR，这里还是主要修复使用问题

2024-03-11 08:44 UTC, RadxaYuntian requested changes

2024-03-11 08:44 UTC, RadxaYuntian commented on src/arm/radxa_rock_5a.c
> +    b->pins[24].pwm.parent_id = 1;   // PWM1_M2
顺序没有改

2024-03-22 09:12 UTC, RadxaYuntian commented
这边也要处理啊

2024-03-22 11:20 UTC, nascs commented
> 这边也要处理啊

等 ROCK PI E 的 PR 合并

2024-03-22 11:41 UTC, RadxaYuntian commented
这两个不影响，你可以先改，然后rock pi e的合并了再rebase

2024-03-22 11:45 UTC, nascs commented
> 这两个不影响，你可以先改，然后rock pi e的合并了再rebase

好的，下周一

2024-03-25 02:40 UTC, nascs commented
> 这边也要处理啊

所有板子的顺序要不要再这一块处理了？

2024-03-25 02:41 UTC, RadxaYuntian commented
你要弄就先有个单独的commit处理格式问题。

2024-03-25 11:36 UTC, RadxaYuntian requested changes
应该是先改格式，然后在加入新代码。并且5a的修改需要添加的时候就是正确的顺序

2024-03-26 08:48 UTC, RadxaYuntian requested changes
你这个添加或减少pwm后要把头文件的数量更新啊

2024-03-26 08:48 UTC, RadxaYuntian commented on src/arm/radxa_cm5_io.c
MRAA_RADXA_CM5_IO_PWM_COUNT还是7

2024-03-26 09:05 UTC, RadxaYuntian requested changes
pwm修正的两个提交合并一下，然后pwm初始化的提交消息就写fix而不是unified。okdo那边已经发现之前的初始化是有问题的

2024-03-26 09:06 UTC, nascs commented
> pwm修正的两个提交合并一下，然后pwm初始化的提交消息就写fix而不是unified。okdo那边已经发现之前的初始化是有问题的

指的是不加 pinmap 会有问题？

2024-03-26 09:45 UTC, RadxaYuntian approved these changes

2024-03-26 09:45 UTC, closed without merging

2024-04-19 08:15 UTC, RadxaYuntian commented
这个可以提交给上游了

2024-04-19 08:21 UTC, nascs commented
> 这个可以提交给上游了

#eclipse/mraa/pull/1129

2024-04-19 08:47 UTC, RadxaYuntian commented
一般链接PR/issue是用`eclipse/mraa#1129`这样的格式，效果：eclipse/mraa#1129