Add radxa zero3 support
RadxaYuntian/mraa pull request #15
Opened 2024-07-12 07:55 UTC by nascs

Zero3 和 3C 的 40 PIN 是一样的

2024-07-12 08:06 UTC, RadxaYuntian requested changes
mraa有文档么？有的话也要更新

2024-07-12 08:06 UTC, RadxaYuntian commented on include/arm/radxa_rock_3c.h
> +#define PLATFORM_NAME_RADXA_ZERO3   "Radxa ZERO 3"
```suggestion
#define PLATFORM_NAME_RADXA_ZERO3    "Radxa ZERO 3"
```

2024-07-12 08:06 UTC, RadxaYuntian commented on src/arm/arm.c
> +                mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_ZERO3))
```suggestion
                 mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_ZERO3))
```

2024-07-12 08:09 UTC, nascs commented
> mraa有文档么？有的话也要更新

好

2024-07-12 08:15 UTC, RadxaYuntian requested changes

2024-07-12 08:15 UTC, RadxaYuntian commented on include/arm/radxa_rock_3c.h
> +#define PLATFORM_NAME_RADXA_ZERO3    "Radxa ZERO 3"
```suggestion
#define PLATFORM_NAME_RADXA_ZERO3     "Radxa ZERO 3"
```

2024-07-12 08:15 UTC, RadxaYuntian commented on src/arm/radxa_rock_3c.c
> +    if (mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_ROCK_3C)) {
不直接替换下面第65行？所以你是真的从来不测试你的代码的么？

2024-07-12 08:15 UTC, RadxaYuntian commented on src/arm/radxa_rock_3c.c
> +        printf("An unknown product detected. Fail early...\n");
用syslog函数

2024-07-12 08:15 UTC, RadxaYuntian commented on src/arm/radxa_rock_3c.c
> +        exit(-1);
```suggestion
        return NULL;
```
你区区一个运行库凭什么把我主程序都给干掉了？

2024-07-12 08:16 UTC, nascs commented
> mraa有文档么？有的话也要更新

pinout 一样的话，是直接在 radxa_rock_3c.md 那里添加 zero3 的相关描述？还是添加一个 radxa_zero3.md？

2024-07-12 08:25 UTC, RadxaYuntian commented
zero 3 单独弄一个吧，然后说明是兼容3c的

2024-07-18 02:57 UTC, RadxaYuntian requested changes

2024-07-18 02:57 UTC, RadxaYuntian commented on docs/radxa_zero3.md
> +Radxa ZERO3 {#_Radxa}
```suggestion
Radxa ZERO 3 {#_Radxa}
```

2024-07-18 02:57 UTC, RadxaYuntian commented on docs/radxa_zero3.md
> +The ZERO 3W and ZERO 3E are basically the same size and model, but differ only in storage and network interfaces.
```suggestion
The ZERO 3W and ZERO 3E differ only in storage and network interfaces. 
```

2024-07-18 02:57 UTC, RadxaYuntian commented on docs/radxa_zero3.md
> +Radxa ZERO 3W/3E is an ultra-small, versatile platform that can be used for a wide variety of applications, including IoT devices, machine learning edge computing, home automation, education, and ent
```suggestion
Radxa ZERO 3 is an ultra-small, versatile platform that can be used for a wide variety of applications, including IoT devices, machine learning edge computing, home automation, education, and entertainment.
```
开始胡言乱语了

2024-07-18 02:57 UTC, RadxaYuntian commented on docs/radxa_zero3.md
> +The Radxa Zero3 40-pin headers' pinout is compatible with the [Radxa ROCK 3C 40-pin headers' pinout](./radxa_rock_3c.md).
```suggestion
The Radxa ZERO 3's GPIO pinout is compatible with the [Radxa ROCK 3C](./radxa_rock_3c.md).
```
然后下面还是复制一份

2024-07-18 02:57 UTC, RadxaYuntian commented on src/arm/radxa_e25.c
> +        return NULL;
回头单独弄个pr

2024-07-18 02:57 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +        return NULL;
回头单独弄个pr

2024-07-18 02:57 UTC, RadxaYuntian commented on src/arm/radxa_rock_3c.c
> +        return NULL;
```suggestion
        free(b);
        return NULL;
```

2024-07-19 10:14 UTC, nascs commented
功能测试 pass.

2024-07-19 10:22 UTC, RadxaYuntian commented
可以了就点request for review

2024-07-25 01:54 UTC, nascs commented
> 可以了就点request for review

这个 pr 没找到 request for review 按钮，有空 review 一下？

2024-07-25 02:35 UTC, RadxaYuntian approved these changes
提交整理一下就可以提给上游了

2024-07-25 02:35 UTC, closed without merging