platform: add Radxa ROCK 5A platform support
RadxaYuntian/mraa pull request #3
Opened 2023-07-26 03:38 UTC by nascs

测试过了，ok 的

2023-09-13 02:38 UTC, nascs commented
你那边也需要同步一下上游

2023-09-18 02:23 UTC, RadxaYuntian requested changes

2023-09-18 02:23 UTC, RadxaYuntian commented on README.md
> +* [Radxa ROCK 5A]()
1. 5A文档呢？
2. 我们的产品按字母顺序排列，把下面ROCK 4的也更新一下
3. 要补上3C的链接

2023-09-18 02:23 UTC, RadxaYuntian commented on api/mraa/types.h
> +    MRAA_RADXA_ROCK_5A = 28,         /**< Radxa ROCK 5 Model A */
编号顺序

2023-09-18 02:23 UTC, RadxaYuntian commented on api/mraa/types.h
> +} mraa_radxa_rock5a_wiring_t;
包含上面用rock_5a而不是rock5a

2023-09-18 02:23 UTC, RadxaYuntian commented on api/mraa/types.hpp
> +    RADXA_ROCK_5A = 28,         /**< Radxa ROCK 5 Model A */
编号顺序

2023-09-18 02:23 UTC, RadxaYuntian commented on api/mraa/types.hpp
> +    RADXA_ROCK5A_PIN40 = 40
ROCK_5A

2023-09-18 02:23 UTC, RadxaYuntian commented on src/arm/arm.c
> -
不要动源文件的空行

2023-09-18 02:23 UTC, RadxaYuntian commented on src/CMakeLists.txt
> +  ${PROJECT_SOURCE_DIR}/src/arm/radxa_rock_5a.c
我们的产品放一起

2023-09-18 02:23 UTC, RadxaYuntian commented on src/arm/arm.c
> +        case MRAA_RADXA_ROCK_5A:
跟3C放一起

2023-09-18 02:23 UTC, RadxaYuntian commented on include/arm/radxa_rock_5a.h
> +#define MRAA_RADXA_ROCK_5A_PWM_COUNT  7
后面有9个pwm

2023-09-18 02:23 UTC, RadxaYuntian commented on src/arm/radxa_rock_5a.c
> +    mraa_radxa_rock_5a_pininfo(b, 11,  4, 11, (mraa_pincapabilities_t){1,1,1,0,0,0,0,0}, "GPIO4_B3");  // i2c7-m3, i2c channel was occupied by i2c7-m0
i2c复用不归mraa管，用户换个overlay就应该可以

2023-09-20 06:34 UTC, nascs commented on README.md
> +* [Radxa ROCK 5A]()
5A 文档有的

2023-09-20 06:38 UTC, RadxaYuntian commented on README.md
> +* [Radxa ROCK 5A]()
有但你这个链接是坏的啊

2023-09-20 06:41 UTC, nascs commented on README.md
> +* [Radxa ROCK 5A]()
3C 的链接后面再提个 pr 添加吧

2023-09-20 06:42 UTC, RadxaYuntian commented on README.md
> +* [Radxa ROCK 5A]()
可以

2023-09-20 07:03 UTC, nascs commented on src/arm/radxa_rock_5a.c
> +    mraa_radxa_rock_5a_pininfo(b, 11,  4, 11, (mraa_pincapabilities_t){1,1,1,0,0,0,0,0}, "GPIO4_B3");  // i2c7-m3, i2c channel was occupied by i2c7-m0
这里 i2c7 的 m0 通道被 es8316 占用了， 换 i2c7-m3 的 overlay 串口会一直报错的， 所以这列把 i2c7-m0 给关了

[  159.691945] es8316 7-0011: ASoC: error at soc_component_write_no_lock on es8316.7-0011: -6
[  159.692110] es8316 7-0011: ASoC: error at soc_component_write_no_lock on es8316.7-0011: -6
[  159.692271] es8316 7-0011: ASoC: error at soc_component_write_no_lock on es8316.7-0011: -6

2023-09-20 09:36 UTC, RadxaYuntian commented on src/arm/radxa_rock_5a.c
> +    mraa_radxa_rock_5a_pininfo(b, 11,  4, 11, (mraa_pincapabilities_t){1,1,1,0,0,0,0,0}, "GPIO4_B3");  // i2c7-m3, i2c channel was occupied by i2c7-m0
那注释应该写I2C-M0 is used by on-board devices

2023-09-20 09:38 UTC, RadxaYuntian commented on api/mraa/types.h
> +} mraa_radxa_rock5a_wiring_t;
`mraa_radxa_rock5a_wiring_t`也要改

2023-09-20 09:40 UTC, RadxaYuntian requested changes

2023-09-20 09:40 UTC, RadxaYuntian commented on api/mraa/types.hpp
>  } RadxaRock5aWiring;
```suggestion
} RadxaRock5AWiring;
```

2023-09-20 09:40 UTC, RadxaYuntian commented on src/CMakeLists.txt
> +  ${PROJECT_SOURCE_DIR}/src/arm/radxa_rock_5a.c
注意文件名顺序

2023-09-20 09:40 UTC, RadxaYuntian commented on src/arm/arm.c
> +        case MRAA_RADXA_ROCK_5A:
注意字母顺序，放在3c下面

2023-09-20 09:53 UTC, RadxaYuntian requested changes

2023-09-20 09:53 UTC, RadxaYuntian commented on src/arm/arm.c
> -
文件本来就有的空行不要去动

2023-09-20 10:19 UTC, RadxaYuntian approved these changes

2023-09-20 10:19 UTC, closed without merging