platform: add Radxa ROCK 5B platform support
RadxaYuntian/mraa pull request #4
Opened 2023-09-04 07:57 UTC by nascs

2023-09-27 07:20 UTC, nascs commented
你这边需要同步一下 eclipse/mraa 上游

2023-09-27 07:23 UTC, nascs commented
READMINE 链接问题，已提了一个 [pr](https://github.com/eclipse/mraa/pull/1115) 到上游了

2023-09-27 07:23 UTC, nascs commented
5B 之前有测试过功能

2023-09-27 07:26 UTC, RadxaYuntian requested changes

2023-09-27 07:26 UTC, RadxaYuntian commented on api/mraa/types.h
> +    MRAA_RADXA_ROCK_5A = 29,        /**< Radxa ROCK 5 Model A */
你自己的分支也要同步

2023-09-27 08:04 UTC, nascs commented on api/mraa/types.h
> +    MRAA_RADXA_ROCK_5A = 29,        /**< Radxa ROCK 5 Model A */
有点奇怪，我仓库那边 74 行是对齐上边的

2023-10-09 02:58 UTC, RadxaYuntian requested changes

2023-10-09 02:58 UTC, RadxaYuntian commented on api/mraa/types.h
> +
1. 多余空行
2. 按照顺序放到5a后面

2023-10-09 02:58 UTC, RadxaYuntian commented on api/mraa/types.hpp
> +
5a后面

2023-10-09 02:58 UTC, RadxaYuntian commented on src/CMakeLists.txt
> +  ${PROJECT_SOURCE_DIR}/src/arm/radxa_rock_5b.c
5a后面

2023-10-09 02:58 UTC, RadxaYuntian commented on src/arm/arm.c
> +        case MRAA_RADXA_ROCK_5B:
5a后面

2023-10-09 02:58 UTC, RadxaYuntian commented on src/arm/radxa_rock_5b.c
> +    mraa_radxa_rock_5b_pininfo(b, 8,  4, 13, (mraa_pincapabilities_t){1,0,0,0,0,1,0,1}, "GPIO0_B5");  // used by fiq_debugger
说清楚什么功能used by fiq_debugger导致不能开启

2023-10-09 04:00 UTC, RadxaYuntian approved these changes

2023-10-09 04:00 UTC, closed without merging