Radxa cm3
RadxaYuntian/mraa pull request #7
Opened 2023-10-23 02:16 UTC by nascs

2023-10-23 02:17 UTC, nascs commented
@RadxaYuntian CM3 IO 和 CM3 + RPI CM4 IO 的 pinout 是一致的

2023-10-23 02:23 UTC, RadxaYuntian commented
那就参考ROCK 4的写法啊，compatible直接匹配两个产品

2023-10-23 02:23 UTC, RadxaYuntian commented
所以我之前说最好停一下，看一下代码复用情况

2023-10-23 02:25 UTC, nascs commented
正有这个想法来着，但是文档要分开吧。

2023-10-23 02:54 UTC, RadxaYuntian commented
你把文档的标题定为Radxa CM3，然后把两个底板写到兼容底板列表里面

2023-10-23 03:48 UTC, RadxaYuntian requested changes

2023-10-23 03:48 UTC, RadxaYuntian commented on docs/radxa_cm3_io.md
这个PR的对象都改成radxa_cm3

2023-10-23 08:04 UTC, RadxaYuntian commented
还要支持 https://github.com/radxa/kernel/pull/233/ 这里的新model

2023-10-24 03:17 UTC, RadxaYuntian requested changes

2023-10-24 03:17 UTC, RadxaYuntian commented on api/mraa/types.h
> +    MRAA_RADXA_CM3 = 33,         /**< Radxa CM3 */
缩进对齐

2023-10-24 03:17 UTC, RadxaYuntian commented on api/mraa/types.hpp
> +    RADXA_CM3 = 33,         /**< Radxa CM3 */
对齐

2023-10-24 03:17 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +const char* radxa_cm3_serialdev[MRAA_RADXA_CM3_UART_COUNT] = { "/dev/ttyS2"};
```suggestion
const char* radxa_cm3_serialdev[MRAA_RADXA_CM3_UART_COUNT] = { "/dev/ttyS2" };
```

2023-10-24 03:17 UTC, RadxaYuntian commented on docs/radxa_cm3.md
> +The Radxa ROCK 3 Compute Module (CM3) is a System on Module (SoM) based on a the Rockchip RK3566 System on Chip (SoC). The CM3 integrates the Central Process Unit (CPU), Power Management Unit (PMU),
```suggestion
The Radxa CM3 is a System on Module (SoM) based on the Rockchip RK3566 System on Chip (SoC). CM3 integrates the Central Process Unit (CPU), Power Management Unit (PMU), DRAM memory, flash storage and wireless connectivity (WiFi 5 and BT 5.0) in a small form factor of just 55mm x 40mm. CM3 uses 3x 100P 0.4mm-pitch Board-to-Board connectors to export various features, and can be combined with the customer's baseboard to build complete products, thereby speeding up the research and development process. 

Currently, CM3 is compatible with Radxa CM3 IO Board and Raspberry Pi CM4 IO Board.
```

我们任何文档都先写中文，再机器翻译成英文

2023-10-24 03:17 UTC, RadxaYuntian commented on docs/radxa_cm3.md
> +Radxa CM3 IO/Radxa CM3 RPI CM4 IO has a 40-pin expansion header. Each pin is distinguished by the color.
```suggestion
Radxa CM3 IO Board and Raspberry Pi CM4 IO Baseboard has compatible 40-pin expansion header. Below pinout applies to both products:
```

2023-10-24 12:42 UTC, nascs commented on docs/radxa_cm3.md
> +The Radxa ROCK 3 Compute Module (CM3) is a System on Module (SoM) based on a the Rockchip RK3566 System on Chip (SoC). The CM3 integrates the Central Process Unit (CPU), Power Management Unit (PMU),
这段是摘抄自 [Radxa docs](https://docs.radxa.com/en/compute-module/cm3/cm3-io-board/overview)

2023-10-25 02:47 UTC, RadxaYuntian commented on docs/radxa_cm3.md
> +The Radxa ROCK 3 Compute Module (CM3) is a System on Module (SoM) based on a the Rockchip RK3566 System on Chip (SoC). The CM3 integrates the Central Process Unit (CPU), Power Management Unit (PMU),
只能说之前的翻译质量太差了

2023-10-25 02:54 UTC, RadxaYuntian requested changes

2023-10-25 02:54 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +    b->chardev_capable = 1;
缩进

2023-10-25 02:54 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +    if ((b->platform_name = PLATFORM_NAME_RADXA_CM3_IO) || (b->platform_name = PLATFORM_NAME_RADXA_CM3_IO_2) || (b->platform_name = PLATFORM_NAME_RADXA_CM3_RPI_CM4_IO))
1. platform已经在src/arm/arm.c里判断了，这里重复判断
2. 对比是==，=的话赋值是永远返回true的
3. 字符串对比要用strcmp之类的函数

2023-10-25 09:40 UTC, RadxaYuntian requested changes

2023-10-25 09:40 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +        b->platform_name = PLATFORM_NAME_RADXA_CM3_IO;
```suggestion
        b->platform_name = PLATFORM_NAME_RADXA_CM3_IO_2;
```
用我们最新的正式名称

2023-10-25 09:40 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +        printf("not Radxa CM3 series !\n");
```suggestion
        printf("An unknown product detected. Fail early...\n");
```

2023-10-26 03:20 UTC, RadxaYuntian requested changes
还有上一次review遗留的问题

2023-10-26 03:20 UTC, RadxaYuntian commented on docs/radxa_cm3.md
> +Radxa CM3 IO Board and Raspberry Pi CM4 IO Baseboard has compatible 40-pin expansion header. Below pinout applies to both products:
```suggestion
Radxa CM3 IO Board and Raspberry Pi CM4 IO Baseboard's 40-pin expansion header are compatible. The following pinout applies to both products:
```

2023-10-26 03:20 UTC, RadxaYuntian commented on include/arm/radxa_cm3.h
> + * Copyright (c) Radxa Limited.
```suggestion
 * Copyright (c) 2023 Radxa Limited.
```

2023-10-26 03:20 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> + * Copyright (c) Radxa Limited.
```suggestion
 * Copyright (c) 2023 Radxa Limited.
```

2023-10-26 03:20 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +       ) {
```suggestion
       mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_CM3_IO__BOARD)) {
```
现有代码风格没有新起一行

2023-10-26 03:20 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +    if(pincapabilities_t.gpio == 1) {
```suggestion
    if (pincapabilities_t.gpio == 1) {
```

2023-10-26 03:20 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +    if(mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_CM3_IO) ||
```suggestion
    if (mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_CM3_IO) ||
```

2023-10-26 03:20 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +    } else if(mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_CM3_RPI_CM4_IO)) {
```suggestion
    } else if (mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_CM3_RPI_CM4_IO)) {
```

2023-10-26 06:18 UTC, RadxaYuntian requested changes

2023-10-26 06:18 UTC, RadxaYuntian commented on src/arm/radxa_cm3.c
> +       mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_CM3_IO_2)) {
```suggestion
        mraa_file_contains("/proc/device-tree/model", PLATFORM_NAME_RADXA_CM3_IO_2)) {
```
缩进和括号内对齐

2023-10-26 06:18 UTC, closed without merging

2023-10-26 06:18 UTC, RadxaYuntian commented
应该没问题了