Radxa cm5 io
RadxaYuntian/mraa pull request #8
Opened 2023-10-30 06:24 UTC by nascs

docs 暂时没有这个链接 https://docs.radxa.com/compute-module/cm5

2023-10-30 06:26 UTC, RadxaYuntian commented
等文档先更新确定了url

2023-10-30 06:29 UTC, RadxaYuntian requested changes
代码结构模仿CM3。我们之后应该会做树莓派的兼容

2023-10-30 06:36 UTC, nascs commented
也就是之后的 CM5 + RPI CM4 IO 的 40 pin 会和我们 CM5 IO 的对齐了?

> 代码结构模仿CM3。我们之后应该会做树莓派的兼容

2023-10-30 06:36 UTC, RadxaYuntian commented
我不知道，问bsp和硬件，他们之前就在调这个

2023-10-30 06:45 UTC, nascs commented
现在的 40 pin 是不一样的，ken 说之前怎样，后面就怎样，40 pin 上做不了像 CM3 + RPI CM4 IO 那样完全兼容 CM3 IO

2023-10-30 06:47 UTC, RadxaYuntian commented on src/arm/radxa_cm5_io.c
> +    // Hardware X2.0
正式版会修改么？

2023-10-30 07:40 UTC, nascs commented on src/arm/radxa_cm5_io.c
> +    // Hardware X2.0
应该是不会，@Ken-Vamrs

2023-10-31 06:07 UTC, nascs commented on src/arm/radxa_cm5_io.c
> +    // Hardware X2.0
> 正式版会修改么？

上午和刘工还有 ken 对过了， 这个现在不好改, CM5 给 RPI CM4 IO 预留的 IO 口不多

2023-10-31 06:51 UTC, RadxaYuntian commented on src/arm/radxa_cm5_io.c
> +    // Hardware X2.0
那也别在代码里面写硬件版本，没有改动写了让人困扰

2023-11-01 07:36 UTC, RadxaYuntian requested changes

2023-11-01 07:36 UTC, RadxaYuntian commented on docs/radxa_cm5_io.md
> +Radxa CM5 IO is a Rockchip RK3588s based SBC(Single Board Computer) by Radxa. It can run android or some Linux distributions. Radxa CM5 IO features an eight core ARM processor, 64bit dual channel 320
cm5 io不是sbc

2023-11-01 07:36 UTC, RadxaYuntian commented on docs/radxa_cm5_io.md
> +- CS0 is occupied by rk806, spi2 on 40 pins can't be used.
https://github.com/radxa/overlays/issues/204 修复后更新

2023-11-01 07:36 UTC, RadxaYuntian commented on src/arm/radxa_cm5_io.c
> +    b->phy_pin_count = MRAA_RADXA_CM5_IO_PIN_COUNT + 1;
这里为什么+1？

2023-11-01 10:20 UTC, nascs commented on src/arm/radxa_cm5_io.c
> +    b->phy_pin_count = MRAA_RADXA_CM5_IO_PIN_COUNT + 1;
mraa_radxa_cm5_io_pininfo(b, 0, -1, -1, (mraa_pincapabilities_t){0,0,0,0,0,0,0,0}, "INVALID");
从 pin 0 开始的

2023-11-01 10:26 UTC, RadxaYuntian requested changes

2023-11-01 10:26 UTC, RadxaYuntian commented on src/arm/radxa_cm5_io.c
> +    mraa_radxa_cm5_io_pininfo(b, 28, -1, -1, (mraa_pincapabilities_t){1,0,0,0,0,0,0,0}, "USB");
上面pinout标得是3.3v

2023-11-01 10:36 UTC, RadxaYuntian approved these changes

2023-11-01 10:36 UTC, closed without merging